version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: rag5-image
    container_name: rag5-container
    ports:
      - "9000:7500"
    volumes:
      - ./app:/app
      - db-data:/database
    command: uvicorn main:app --host 0.0.0.0 --port 7500 --reload
    networks:
      - app-network


  ollama:
    image: ollama/ollama
    container_name: ollama-container
    volumes:
      - ollama-volume:/root/.ollama
    ports:
      - "8500:11434"
    networks:
      - app-network
  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    name: rag5-network
    driver: bridge

volumes:
  db-data:
  ollama-volume:
