version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: rag5-image
    container_name: rag5-container
    ports:
      - "9000:7500"
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 7500 --reload
